## Configuracion de Spring
spring:
  application:
    name: libros

## Configuracion de Instancia
server:
  port: ${PORT:8080}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:ms-inventory-libros}

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE